openapi: 3.1.0
info:
  title: IDeSyDe OpenAPI description
  version: 0.6.3
paths:
  /decision:
    post:
      responses:
        "200":
          description: "Uploaded"
      parameters:
      - name: session
        in: query
        schema:
          type: string

