[package]
name = "idesyde-core-derive"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
idesyde-core = { path = "../rust-core" }
quote.workspace = true  
syn.workspace = true  
