addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "1.2.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native"    % "0.4.3")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.9.13")
addSbtPlugin("com.github.sbt"   % "sbt-unidoc"          % "0.5.0")
addSbtPlugin("com.github.sbt"   % "sbt-site-paradox"    % "1.5.0-RC2")
