libraryDependencies += "io.github.forsyde"  % "forsyde-io-java-core" % "0.5.9"
libraryDependencies += "org.apache.commons" % "commons-math3"        % "3.6.1"
libraryDependencies += "com.outr"          %% "scribe"               % "3.5.5"
libraryDependencies += "com.lihaoyi"       %% "upickle"              % "1.4.0"
libraryDependencies += "org.jgrapht"        % "jgrapht-core"         % "1.5.1"
libraryDependencies += "org.jgrapht"        % "jgrapht-opt"          % "1.5.1"
libraryDependencies += "org.scalanlp"      %% "breeze"               % "2.0.1-RC1"
