openapi: 3.1.0
info:
  title: IDeSyDe OpenAPI description
  version: 0.6.3
servers:
- url: /
paths:
  /decision:
    post:
      parameters:
      - explode: true
        in: query
        name: session
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: Uploaded
components:
  schemas: {}

