---
name: "Release nightly out of the develop branch"

on: workflow_dispatch
jobs:
  publish-java-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly development Build"
    - name: Set up JDK
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "graalvm-ce-java11@21.1.0"
    - name: Get scala version
      id: get_scala_version
      run: |
        cd ${{ github.workspace }}
        echo "::set-output name=scalaVersion::$(sbt --error 'print cli/scalaVersion')"
        echo "::set-output name=version::$(sbt --error 'print cli/version')"
    - name: Build assembly with sbt
      run: |
        cd ${{ github.workspace }}
        sbt assembly
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/cli/target/scala-${{ steps.get_scala_version.outputs.scalaVersion }}/cli-assembly-${{ steps.get_scala_version.outputs.version }}.jar
        asset_name: idesyde-nightly-standalone.jar
        tag: "nightly"
        overwrite: true
        body: "Executable IDeSyDe standalone jar"
