---
name: "Building executables"

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    types: [opened, reopened]

concurrency:
  group: Building executables @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-scala-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java:
          - "openjdk@1.11.0"
          - "openjdk@1.15.0"
          - "openjdk@1.17.0"
          - "zulu@1.11.0"
          - "zulu@1.15.0"
          - "zulu@1.17.0"
          # - "amazon-corretto@1.17.0-0.35.1"
          - "amazon-corretto@1.11.0-11.9.1"
          - "graalvm-ce-java11@21.1.0"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java }}
    - name: Build assembly with sbt
      run: |
        cd ${{ github.workspace }}
        sbt publishModules
  test-rust-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build rust
      run: |
        cd ${{ github.workspace }}
        cargo build -r