---
name: "Building IDeSyDe modules and executables"

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    types: [opened, reopened]

concurrency:
  group: test-build @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-scala-build-on-linux:
    strategy:
      matrix:
        jdk: [temurin@17, amazon-corretto@17, zulu@17, microsoft@17]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build scala
      run: |
        cd ${{ github.workspace }}
        curl -sL https://github.com/Jabba-Team/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
        jabba install ${{ matrix.jdk }}
        jabba alias default ${{ matrix.jdk }}
        curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux-static.gz" | gzip -d > cs
        chmod +x ./cs
        ./cs setup --yes
        sbt publishModules
  test-java-build-on-linux:
    strategy:
      matrix:
        jdk: [temurin@17, amazon-corretto@17, zulu@17, microsoft@17]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Java
      run: |
        cd ${{ github.workspace }}
        curl -sL https://github.com/Jabba-Team/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
        jabba install ${{ matrix.jdk }}
        jabba alias default ${{ matrix.jdk }}
        ./gradlew publishModules        
  test-rust-build-on-linux:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build rust
      run: |
        cd ${{ github.workspace }}
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        rustup target add ${{ matrix.target }}
        carbo build --release --target ${{ matrix.target }}