---
name: "Building IDeSyDe modules and executables"

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    types: [opened, reopened]

concurrency:
  group: test-build @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-scala-build:
    strategy:
      matrix:
        jdk_base: ["eclipse-temurin:11-alpine", "eclipse-temurin:17-alpine", "amazoncorretto:11-alpine-jdk", "amazoncorretto:17-alpine-jdk"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.8
    - name: Build scala
      run: |
        cd ${{ github.workspace }}
        earthly +build-scala-all --jdk_base="${{ matrix.jdk_base }}"
  test-rust-build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.8
    - name: Build rust
      run: |
        cd ${{ github.workspace }}
        earthly +build-rust-linux-host --targets="${{ matrix.target }}"